# Generated by Django 2.0.7 on 2018-07-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
