# Generated by Django 2.0.7 on 2018-07-31 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_visitors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitors',
            new_name='Visitor',
        ),
    ]
