# Generated by Django 2.0.7 on 2018-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180906_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('owner_email', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('announcement', models.CharField(max_length=200)),
                ('footer', models.CharField(max_length=100)),
            ],
        ),
    ]
