# Generated by Django 2.0.7 on 2018-09-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='logo',
            new_name='logo_url',
        ),
    ]
