# Generated by Django 2.0.7 on 2018-07-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180719_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ifvalid',
            field=models.BooleanField(default=0),
        ),
    ]
