# Generated by Django 2.0.7 on 2018-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20180727_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ifparent',
            field=models.BooleanField(default=True),
        ),
    ]
