# Generated by Django 2.0.7 on 2018-07-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_comment_ifparent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ifparent',
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
