# Generated by Django 2.0.7 on 2018-07-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20180727_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
        migrations.AddField(
            model_name='comment',
            name='ifparent',
            field=models.BooleanField(default=True),
        ),
    ]
