# Generated by Django 2.0.7 on 2018-07-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20180727_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_time']},
        ),
    ]
